(()=>{'use strict';
const data=window.FIELD_NOTES_DATA,grid=document.getElementById('route-grid'),dialog=document.getElementById('route-dialog');
if(!data||!Array.isArray(data.routes)){grid.textContent='The walking journal could not be loaded. Please refresh the page.';return;}
const motionPreference=matchMedia('(prefers-reduced-motion: reduce)');let reduce=motionPreference.matches,globalPaused=false,lastTime=0,dialogIndex=null;
const localDate=t=>new Intl.DateTimeFormat('en-GB',{day:'2-digit',month:'short',year:'numeric',timeZone:'Asia/Hong_Kong'}).format(new Date(t)),localTime=t=>new Intl.DateTimeFormat('en-GB',{hour:'2-digit',minute:'2-digit',hourCycle:'h23',timeZone:'Asia/Hong_Kong'}).format(new Date(t));
const pad=n=>String(n).padStart(2,'0'),duration=n=>`${Math.floor(n/60)}h ${pad(n%60)}m`,pace=n=>`${Math.floor(n/60)}′${pad(n%60)}″`;
document.getElementById('total-routes').textContent=data.summary.routes;
document.getElementById('total-distance').innerHTML=`${data.summary.distanceKm.toFixed(1)}<small> km</small>`;
document.getElementById('total-time').innerHTML=`${Math.floor(data.summary.elapsedMinutes/60)}<small> h </small>${pad(data.summary.elapsedMinutes%60)}<small> m</small>`;
document.getElementById('total-areas').textContent=data.summary.areas;
const ns='http://www.w3.org/2000/svg',states=[];
function metrics(r){const wrapper=document.createElement('div');wrapper.className='route-metrics';for(const [value,label] of [[r.distanceKm.toFixed(2),'Distance · km'],[duration(r.elapsedMinutes),'Elapsed time'],[pace(r.paceSeconds),'Avg. pace /km']]){const block=document.createElement('div'),v=document.createElement('strong'),l=document.createElement('span');v.textContent=value;l.textContent=label;block.append(v,l);wrapper.append(block);}return wrapper;}
function art(r,interactive=false){const container=document.createElement('div');container.className='route-art';const svg=document.createElementNS(ns,'svg');svg.setAttribute('viewBox','0 0 300 300');svg.setAttribute('role','img');svg.setAttribute('aria-label',r.title+' — complete recorded route');svg.classList.add('route-svg');const strokes=[];for(const segment of r.segments){const d=segment.map((p,i)=>(i?'L':'M')+(150+p[0]*232).toFixed(2)+' '+(150+p[1]*232).toFixed(2)).join(' ');const ghost=document.createElementNS(ns,'path');ghost.setAttribute('d',d);ghost.classList.add('route-ghost');svg.append(ghost);const p=document.createElementNS(ns,'path');p.setAttribute('d',d);p.classList.add('route-line');svg.append(p);strokes.push(p);}const dot=document.createElementNS(ns,'circle');dot.classList.add('route-dot');dot.setAttribute('r','3.2');svg.append(dot);container.append(svg);const north=document.createElement('span');north.className='north';north.textContent='↑ N';const caption=document.createElement('span');caption.className='map-caption';caption.textContent='COMPLETE GPS TRACE';container.append(north,caption);return {element:container,strokes,dot,lengths:[],total:0,route:r,interactive,mounted:false};}
function initMap(view){
 view.mounted=true;
 const svg=view.element.querySelector('.route-svg');
 const el=document.createElement('div');el.className='real-map';el.setAttribute('aria-label',view.route.title+' vector map');view.element.prepend(el);
 const bounds=new maplibregl.LngLatBounds();for(const segment of view.route.geoSegments)for(const p of segment)bounds.extend([p[1],p[0]]);
 let map;
 try{map=new maplibregl.Map({container:el,style:'https://tiles.openfreemap.org/styles/liberty',bounds,fitBoundsOptions:{padding:30,maxZoom:17},interactive:view.interactive,attributionControl:false,dragRotate:false,pitchWithRotate:false,maxPitch:0,renderWorldCopies:false,fadeDuration:0});}
 catch(error){el.remove();view.element.querySelector('.map-caption').textContent='Vector map unavailable · route only';return;}
 view.map=map;svg.classList.add('map-route-overlay');
 view.element.querySelector('.north').remove();view.element.querySelector('.map-caption').remove();
 map.addControl(new maplibregl.AttributionControl({compact:true}),'bottom-right');
 if(view.interactive){map.addControl(new maplibregl.NavigationControl({showCompass:false}),'top-right');map.addControl(new maplibregl.ScaleControl({unit:'metric'}),'bottom-left');map.touchZoomRotate.disableRotation();}
 const endpoints=[view.route.geoSegments[0][0],view.route.geoSegments.at(-1).at(-1)].map((p,i)=>{const c=document.createElementNS(ns,'circle');c.setAttribute('r','4');c.setAttribute('fill','#fbf9f2');c.setAttribute('stroke',i?'#744e35':'#496937');c.setAttribute('stroke-width','2');const title=document.createElementNS(ns,'title');title.textContent=i?'Finish':'Start';c.append(title);svg.append(c);return {point:p,circle:c};});
 const ghosts=[...svg.querySelectorAll('.route-ghost')];
 function project(){
  const width=el.clientWidth,height=el.clientHeight;if(!width||!height)return;
  svg.setAttribute('viewBox',`0 0 ${width} ${height}`);
  view.route.geoSegments.forEach((segment,i)=>{const d=segment.map((p,j)=>{const point=map.project([p[1],p[0]]);return(j?'L':'M')+point.x.toFixed(2)+' '+point.y.toFixed(2);}).join(' ');view.strokes[i].setAttribute('d',d);ghosts[i].setAttribute('d',d);});
  for(const endpoint of endpoints){const p=map.project([endpoint.point[1],endpoint.point[0]]);endpoint.circle.setAttribute('cx',p.x);endpoint.circle.setAttribute('cy',p.y);}
  measure(view);paint(view,view.progress??0);
 }
 map.on('move',project);map.on('resize',project);project();
 view.resizeObserver=new ResizeObserver(()=>{map.resize();if(!view.interactive)map.fitBounds(bounds,{padding:30,maxZoom:17,duration:0});project();});view.resizeObserver.observe(el);
 map.on('load',()=>{
  for(const layer of map.getStyle().layers){
   if(layer.type==='background')map.setPaintProperty(layer.id,'background-color','#f2efe4');
   if(layer.type==='fill'&&layer['source-layer']==='water')map.setPaintProperty(layer.id,'fill-color','#c3d9d6');
   if(layer.type==='symbol'&&layer.layout?.['text-field']){map.setPaintProperty(layer.id,'text-color','#394533');map.setPaintProperty(layer.id,'text-halo-color','#fbf9f2');map.setPaintProperty(layer.id,'text-halo-width',1.2);}
  }
  project();
 });
 let notice=null;map.on('error',()=>{if(notice)return;notice=document.createElement('span');notice.className='tile-notice';notice.textContent='Some map details could not load';view.element.append(notice);});
 el.querySelector('canvas').addEventListener('webglcontextlost',()=>{if(notice)return;notice=document.createElement('span');notice.className='tile-notice';notice.textContent='Map paused · refresh to restore';view.element.append(notice);});
 el.querySelector('canvas').addEventListener('webglcontextrestored',()=>{notice?.remove();notice=null;project();});
}

function measure(view){if(window.maplibregl&&!view.mounted)initMap(view);view.lengths=view.strokes.map(p=>p.getTotalLength());view.total=view.lengths.reduce((a,b)=>a+b,0);view.strokes.forEach((p,i)=>p.style.strokeDasharray=String(view.lengths[i]));}
function paint(view,progress){view.progress=progress;if(!view.total)return;let remaining=view.total*progress,active=null;view.strokes.forEach((path,i)=>{const len=view.lengths[i],done=Math.max(0,Math.min(len,remaining));path.style.strokeDashoffset=String(len-done);if(remaining>=0&&remaining<=len)active={path,done};remaining-=len;});if(progress>=1){view.dot.style.display='none';return;}view.dot.style.display='';if(active){const p=active.path.getPointAtLength(active.done);view.dot.setAttribute('cx',p.x);view.dot.setAttribute('cy',p.y);}}
function textState(state){if(reduce)return 'Full route';if(globalPaused||state.paused)return 'Paused';return state.phase>=7000?'Taking it in':'Tracing the walk';}
function updateButtons(){document.getElementById('all-motion').textContent=globalPaused?'▶ Resume all replays':'Ⅱ Pause all replays';document.getElementById('all-motion').setAttribute('aria-pressed',String(globalPaused));states.forEach(s=>{s.button.textContent=s.paused?'Resume':'Pause';s.button.setAttribute('aria-pressed',String(s.paused));});if(dialogIndex!==null){const s=states[dialogIndex];document.getElementById('dialog-motion').textContent=s.paused?'Resume this replay':'Pause this replay';}}
data.routes.forEach((r,index)=>{const card=document.createElement('article');card.className='route-card';const mapButton=document.createElement('div');mapButton.className='art-button';mapButton.setAttribute('aria-label','Open '+r.title);const view=art(r);mapButton.append(view.element);const expand=document.createElement('button');expand.type='button';expand.className='map-expand';expand.setAttribute('aria-label','Expand '+r.title);expand.textContent='↗';mapButton.append(expand);const body=document.createElement('div');body.className='route-body';const meta=document.createElement('div');meta.className='route-meta';const num=document.createElement('span');num.textContent='WALK / '+pad(index+1);const month=document.createElement('span');month.textContent=localDate(r.startTime);meta.append(num,month);const heading=document.createElement('h3');heading.style.margin='0';const title=document.createElement('button');title.type='button';title.className='route-title';title.textContent=r.title;heading.append(title);const description=document.createElement('p');description.className='route-description';description.textContent=['A small journey, kept in the collection.','A longer trace of time spent outside.','One more line in the walking journal.'][index];const end=document.createElement('div');end.className='route-end';const status=document.createElement('span');status.className='route-state';status.textContent='Tracing the walk';const button=document.createElement('button');button.type='button';button.className='single-motion';button.textContent='Pause';button.setAttribute('aria-label','Pause or resume '+r.title);button.setAttribute('aria-pressed','false');end.append(status,button);body.append(meta,heading,description,metrics(r),end);card.append(mapButton,body);grid.append(card);measure(view);const state={phase:0,paused:false,view,status,button,visible:true};states.push(state);button.addEventListener('click',()=>{state.paused=!state.paused;updateButtons();});expand.addEventListener('click',()=>openRoute(index));title.addEventListener('click',()=>openRoute(index));if('IntersectionObserver'in window){const observer=new IntersectionObserver(entries=>{state.visible=entries[0].isIntersecting;},{rootMargin:'80px'});observer.observe(card);}});
let dialogView=null;
function openRoute(index){dialogIndex=index;const r=data.routes[index];document.getElementById('dialog-title').textContent=r.title;dialog.querySelector('.dialog-date').textContent=localDate(r.startTime)+' · '+localTime(r.startTime)+'–'+localTime(r.endTime)+' HKT / WALK '+pad(index+1);dialogView=art(r,true);dialog.querySelector('.dialog-art').replaceChildren(dialogView.element);dialog.querySelector('.dialog-stats').replaceChildren(metrics(r));dialog.showModal();measure(dialogView);paint(dialogView,reduce?1:Math.min(states[index].phase/7000,1));updateButtons();}
document.getElementById('close-dialog').addEventListener('click',()=>dialog.close());dialog.addEventListener('click',event=>{if(event.target===dialog){const b=dialog.getBoundingClientRect();if(event.clientX<b.left||event.clientX>b.right||event.clientY<b.top||event.clientY>b.bottom)dialog.close();}});dialog.addEventListener('close',()=>{if(dialogView?.resizeObserver)dialogView.resizeObserver.disconnect();if(dialogView?.map)dialogView.map.remove();dialogView=null;dialogIndex=null;});document.getElementById('dialog-motion').addEventListener('click',()=>{if(dialogIndex===null)return;states[dialogIndex].paused=!states[dialogIndex].paused;updateButtons();});document.getElementById('all-motion').addEventListener('click',()=>{globalPaused=!globalPaused;updateButtons();});
function reduced(){reduce=motionPreference.matches;document.getElementById('all-motion').hidden=reduce;document.getElementById('dialog-motion').hidden=reduce;states.forEach(s=>{s.button.hidden=reduce;if(reduce)paint(s.view,1);});}motionPreference.addEventListener('change',reduced);reduced();
function frame(t){const delta=lastTime?Math.min(t-lastTime,80):0;lastTime=t;states.forEach((s,i)=>{if(!reduce&&!document.hidden&&!globalPaused&&!s.paused&&(s.visible||dialogIndex===i))s.phase=(s.phase+delta)%10000;const progress=reduce?1:Math.min(s.phase/7000,1);if(s.visible)paint(s.view,progress);const label=textState(s);if(s.status.textContent!==label)s.status.textContent=label;if(dialogIndex===i&&dialogView)paint(dialogView,progress);});requestAnimationFrame(frame);}requestAnimationFrame(frame);
})();
